Prevent NoMethodError and beautified
Prevent from the Error "in 'read_next_object_from_unzipped': undefined method '[]' for nil:NilClass (NoMethodError)" in case of info == nil: The line "object_size = info[2].to_i(16)" caused an error.